src/App.tsx

setting: 세팅동작 테스트

---

src/index.css

- 폰트 설정 (Pretendard, Noto Sans KR)
- 디자인 토큰 변수화 (폰트, 색상, 반경)
- 다크모드 지원
- 반응형 레이아웃 기본 설정
글로벌 CSS를 설정하였습니다.
close #7 

feat: 글로벌 스타일 시스템 구축

---

src/index.css

feat: 글로벌 스타일 시스템 추가 구축

---

src/components/common/TextInput/TextInput.stories.tsx
src/components/common/TextInput/TextInput.style.ts
src/components/common/TextInput/TextInput.tsx

type에 email/password를 넣어 해당 부분은 유효성 검사를 할 수 있도록 구현했습니다. 
input 컴포넌트 사용하실 때 아래의 내용들 참고하셔서 작성하시면 됩니다.
label, placeholder는 옵션으로 필요한 부분만 사용하시면 되고 나머지 부분은 필수값인데 name을 제외한 부분은 default 값을 지정해서 수정이 필요한 부분만 써서 쓰시면 됩니다 ! 
name   =>  입력 필드 이름
type = "text"  =>  입력 필드 형식
label => 입력 필드 라벨
placeholder => 입력 필드 플레이스홀더
required = true => 필수 입력
maxLength = 20 => 최대 입력 길이
minLength = 2 => 최소 입력 길이

feat: textInput 컴포넌트 구현 및 스토리북 추가

---

.storybook/preview.ts
src/components/common/TextButton/TextButton.stories.tsx
src/components/common/TextButton/TextButton.style.ts
src/components/common/TextButton/TextButton.tsx

- 텍스트형식 버튼(회원가입, 아이디 찾기, 탈퇴하기) 제작
- 스토리북에 글로벌 스타일 적용되지 않는 문제 해결
close #14

feat: TextButton 컴포넌트 제작, 스토리북에 글로벌 스타일 적용

---

src/components/common/EditDeleteModal/EditDeleteModal.stories.tsx
src/components/common/EditDeleteModal/EditDeleteModal.style.ts
src/components/common/EditDeleteModal/EditDeleteModal.tsx

- 이 컴포넌트는 수정/삭제 모달입니다. 위치는 절대 위치로 설정해야 합니다.
- 수정/삭제 클릭시 실행할 함수를 전달하여야 합니다.
close #23

feat: 수정/삭제 모달 컴포넌트 제작

---

src/components/common/Button/Button.stories.tsx
src/components/common/Button/Button.style.ts
src/components/common/Button/Button.tsx

- 버튼 컴포넌트 스토리북 경로 변경
- 버튼 타입 primaryMicro, whiteMicro 추가 제작
close #32

refactor: 버튼 컴포넌트 스토리북 경로 수정, 버튼 타입 추가 제작

---

src/components/common/EditDeleteModal/EditDeleteModal.stories.tsx
src/components/common/TextButton/TextButton.stories.tsx

- 텍스트버튼, 수정/삭제 모달 스토리북 경로 변경
close #34

refactor: 텍스트버튼, 수정/삭제 모달 스토리북 경로 변경

---

src/components/common/DeleteConfirm/DeleteConfirm.stories.tsx
src/components/common/DeleteConfirm/DeleteConfirm.style.ts
src/components/common/DeleteConfirm/DeleteConfirm.tsx

- text값에 모달에 띄울 메세지를 입력해주세요.
- 취소/삭제를 누를때 실행할 함수를 전달해주세요.
`text: string;`
`onClickDelete: () => void;`
`onClickCancel: () => void;`
close #28

feat: 삭제 확인 모달 구현

---

src/components/common/Toggle/Toggle.stories.tsx
src/components/common/Toggle/Toggle.style.ts
src/components/common/Toggle/Toggle.tsx

- 토글 컴포넌트 제작
`isOn: boolean;` 토글 활성화 유무
`onClick: () => void;` 토글 클릭시 사용될 함수
- close #36

feat: 토글 컴포넌트 제작

---

src/components/common/TextSetting/TextSetting.style.ts
src/components/common/TextSetting/TextSetting.tsx

폰트 사이즈 20px, bold 로 설정
스토리북은 따로 작성 안했습니다 
- ex) close #42

design:텍스트 css 설정

---

src/components/layout/RootLayout/RootLayout.style.tsx
src/index.css

- 루트레이아웃을 수정했습니다.
충돌 위험이 있어서 `RootLayout.tsx`는 올리지 않았고 적용이 필요합니다.
```tsx
import { Outlet } from "react-router-dom";
import * as Style from "./RootLayout.style";
function RootLayout() {
return (
<Style.RootLayoutWrapper>
<header>Header</header>
<main>
<Outlet />
</main>
<footer>Bottom Navigation</footer>
</Style.RootLayoutWrapper>
);
}
export default RootLayout;
```
`import`, `Style.RootLayoutWrapper`만 추가해주면 됩니다.
적용하면 다음과 같이 나타납니다.
-close #49

design: rootlayout css 설정

---

src/components/layout/NavBar/NavBar.style.ts
src/components/layout/NavBar/NavBar.tsx
src/components/layout/RootLayout/RootLayout.tsx

hover 했을 때 색상 변경되고, Link를 넣어서 클릭하면 해당 페이지로 이동할 수 있게 구현
- ex) close #45

feat:하단 내비게이션바 구현

---

src/pages/categories/CategoriesPage.tsx

```html
<Button
children="카테고리 만들기"
buttonType="primaryLarge"
type="button"
isHoverEffect={true}
/>
``` 
- ex) close #66

fix: 버튼 컴포넌트 type 추가

---

src/components/common/Button/Button.tsx
src/components/common/DeleteConfirm/DeleteConfirm.tsx
src/components/common/EditDeleteModal/EditDeleteModal.style.ts
src/components/common/EditDeleteModal/EditDeleteModal.tsx
src/components/common/TextButton/TextButton.tsx
src/components/common/Toggle/Toggle.tsx

- css파일 import명을 Style에서 Styled로 변경
- 기존 red로 사용되던 색상을 --color-red로 변경
- close #71

refactor: 스타일 파일 import 변수명 변경 및 빨간색 컬러 변경

---

package.json
src/App.tsx
src/hooks/useToast.ts

`const { showToast } = useToast()`
`showToast(message, type)`  
`message: string`
`type: "error" | "success" | "warning" | "info`
- close #69

feat: 토스트 커스텀훅 구현

---

src/components/common/EditDeleteModal/EditDeleteModal.style.ts
src/components/common/EditDeleteModal/EditDeleteModal.tsx
src/components/feature/CategoryList/CategoryList.tsx
src/index.css

```html
<EditDeleteModal
top={-10}
left={-55}
onClickEdit={handleEditClick}
onClickDelete={handleDeleteClick}
isVisible={isVisible} 
/>
``` 
isVisible=true일 때 fadeIn 애니메이션 실행되어서 자연스럽게 모달창이 나타남
- ex) close #75

design: 수정/삭제 모달창 수정

---

src/components/common/Button/Button.stories.tsx
src/components/common/ScheduleList/ScheduleItem.stories.tsx
src/components/common/SelectList/Category/Category.stories.tsx
src/components/common/TimeInput/TimeInput.stories.tsx
src/components/common/TodoList/TodoItem.stories.tsx
src/components/common/Toggle/Toggle.stories.tsx

- 페이지 작업 중 공통 컴포넌트의 props가 변경된 게 스토리북에 적용 되지 않은 문제 해결
close #93

fix: 스토리북 오류 해결

---

src/components/common/Button/Button.tsx
src/hooks/useEditPage.ts
src/pages/mypage/MyPage.style.ts
src/pages/mypage/MyPage.tsx
src/pages/mypage/edit/MyEditPage.style.ts
src/pages/mypage/edit/MyEditPage.tsx

마이페이지와 내 정보 수정 페이지를 퍼블리싱 했습니다.
루트 레이아웃 적용 전이어서 다른 작업 이후 css 수정할 계획입니다.
- close #92

design: 마이페이지 및 내 정보 수정 페이지 퍼블리싱

---

src/apis/apiService.ts
src/apis/todoAPI.ts
src/hooks/queries/usePersonalTodos.ts
src/types/todo.types.ts

- apiClient 생성
- get, post, patch, delete 함수 생성
- 예시 함수 생성
close #101

feat: API 인스턴스 생성

---

eslint.config.js
src/components/feature/main/ScheduleList/ScheduleList.tsx
src/hooks/queries/usePersonalTodos.ts
src/hooks/useMainPage.ts
vercel.json

- 배포 관련 설정 작업
- 변경점
- 사용되지 않거나 타입이 없는 변수들이 오류로 잡혀서 배포 테스트를 위해 임시 처리 해놓았습니다.
- "안쓰는 변수 임시 처리" 커밋 확인해주세요 (ScheduleList.tsx, useMainPage.ts)
- 배포 주소: https://web-1-1-all-i-fe.vercel.app/
- close #111

chore: 배포 관련 설정

---

src/components/feature/notifications/GroupInviteForm/GroupInviteForm.style.ts
src/components/feature/notifications/GroupInviteForm/GroupInviteForm.tsx
src/components/feature/notifications/ScheduleForm/ScheduleForm.style.ts
src/components/feature/notifications/ScheduleForm/ScheduleForm.tsx
src/pages/notifications/Notifications.style.ts
src/pages/notifications/NotificationsPage.tsx
src/types/notification.ts

feat: 알림 페이지 퍼블리싱

---

src/store/useAuthStore.ts

- zustand 미들웨어인 `persist` 를 활용해서 새로고침 시에도 토큰을 가져와서 사용할 수 있도록 수정했습니다.
- close #124

hotfix: 새로고침 해도 토큰 유지

---

src/apis/groupTodos.ts
src/apis/groups.ts
src/components/common/SelectList/Group/GroupSelect.tsx
src/components/form/TodoScheduleForm/TodoScheduleForm.tsx
src/components/form/TodoScheduleForm/utils.ts
src/hooks/queries/index.ts
src/hooks/queries/useGroupTodos.ts
src/hooks/queries/usePersonalSchedules.ts
src/hooks/useTodoScheduleForm.ts
src/pages/group/todo/edit/GroupTodoEditPage.tsx
src/pages/group/todo/new/GroupTodoNewPage.tsx
src/types/apiRequest.type.ts
src/types/apiResponse.type.ts
src/types/select.types.ts

- 그룹 투두 생성/수정 API 타입 작성
- 그룹 투두 생성/수정 API 생성
- 그룹 투두 생성/수정 API 연결
- 그룹 멤버 선택 컴포넌트 수정
- close #126

feat: 그룹 투두 생성/수정 API 연결

---

src/apis/groupSchdules.ts
src/hooks/queries/index.ts
src/hooks/queries/useGroupSchedules.ts
src/hooks/useTodoScheduleForm.ts
src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
src/pages/group/schedule/new/GroupScheduleNewPage.tsx
src/pages/group/todo/edit/GroupTodoEditPage.tsx
src/pages/group/todo/new/GroupTodoNewPage.tsx
src/types/apiRequest.type.ts

- 그룹 일정 관련 API 함수 제작
- 그룹 일정 관련 훅 제작
- 그룹 일정 생성 API 연결
- 그룹 일정 수정 API 연결
- handleFormValidation 함수 수정
- close #131

feat: 그룹 일정 생성/수정 API 연결

---

src/apis/groups.ts
src/components/feature/group/GroupPick/GroupPick.style.ts
src/components/feature/group/GroupPick/GroupPick.tsx
src/components/feature/group/MainList/GroupList.tsx
src/components/feature/group/ScheduleItem/GroupScheduleItem.tsx
src/components/feature/group/TodoItem/GroupTodoItem.style.ts
src/components/feature/group/TodoItem/GroupTodoItem.tsx
src/hooks/queries/useGroupSchedules.ts
src/hooks/queries/useGroupTodos.ts
src/hooks/queries/useGroups.ts
src/hooks/useUserNames.ts
src/pages/group/GroupPage.tsx

- 그룹 투두 Done 된 인원 초록색 글씨로 이름 표현
- 모든 인원 done 된 경우 투두 체크되고 줄쳐짐
-  그룹 투두 삭제 개발 완료
- 그룹 일정 삭제 개발 완료
- 그룹 삭제 개발 완료 (그룹 리스트에서 쓰레기통 버튼)
- 드롭다운 리스트 배경 넣기 완료
- $ 에러 수정
- ex) close #147

feat: 그룹 투두 개발 및 코드 수정

---

src/components/layout/Header/Header.tsx

fix: 헤더 에러 해결

---

src/components/common/SelectList/Group/GroupSelect.tsx
src/components/layout/Header/Header.tsx
src/components/layout/Header/headerConfig.ts
src/pages/categories/CategoriesPage.tsx
src/pages/categories/edit/CategoriesEditPage.tsx
src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
src/pages/group/todo/edit/GroupTodoEditPage.tsx

fix:그룹멤버 선택 에러 수정 및 코드 수정

---

src/components/common/Calendar/Calendar.style.ts
src/components/common/Calendar/Calendar.tsx
src/components/feature/GroupNewPage/MemberList.style.ts
src/components/feature/GroupNewPage/MemberList.tsx
src/components/layout/Header/Header.style.ts
src/hooks/useChat.ts
src/hooks/useCircleInput.ts
src/hooks/useGroupEditForm.ts
src/hooks/useGroupNewForm.ts
src/hooks/useMainPage.ts
src/pages/group/GroupPage.tsx
src/pages/group/edit/GroupEditPage.tsx
src/pages/group/noData/GroupNoData.tsx
src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
src/pages/group/schedule/new/GroupScheduleNewPage.tsx
src/pages/main/MainPage.tsx
src/pages/mypage/MyPage.style.ts
src/pages/mypage/MyPage.tsx

- 메인페이지 그룹 투두 버그 수정
- 달력 선택 날짜 기능 추가
- 레이아웃 조정
- 그룹 수정 페이지 예외처리
- 디버깅용 콘솔 로그 주석처리
close #165

fix: 버그 수정

---

index.html
src/apis/apiService.ts
src/components/common/SelectList/Category/Category.stories.tsx
src/components/common/SelectList/Group/GroupSelect.stories.tsx
src/components/feature/header/AlarmIcon.tsx
src/hooks/queries/usePersonalGroupSchedules.ts
src/hooks/queries/usePersonalSchedules.ts
src/hooks/queries/usePersonalTodos.ts
vercel.json

- vercel.json 수정
- 스토리북 컴포넌트 변경 사항에 맞게 변경
- hooks폴더의 파일들에서 안쓰는 import문 삭제
- 개발, 배포 버전에서 BASE_URL 다르게 설정
- SSE 재연결 코드 추가 (Vercel 무료 플랜은 한번 연결 시 30초 정도 유지)
- index.html에 Mixed content 해결하는 meta 태그 조건부로 추가
- close #161

fix: 배포 관련 오류 해결
