src/components/common/TextButton/TextButton.stories.tsx
src/components/common/TextButton/TextButton.tsx

- 버튼안에 들어가는 글씨를 기존 props로 전달받는 형식에서 children으로 변경
close #20

refactor: 텍스트버튼 컴포넌트 수정

---

src/components/common/Circle/Circle.stories.tsx
src/components/common/Circle/Circle.style.tsx
src/components/common/Circle/Circle.tsx
src/components/common/Circle/CircleInput.stories.tsx
src/components/common/Circle/CircleInput.tsx
src/hooks/useCircleInput.ts
src/index.css

- 카테고리에 사용되는 원형 색상을 퍼블리싱했습니다.
이때 카테고리 리스트에서 보여주는 원형 색은 color props를 통해 색을 지정해주면 됩니다.
- 카테고리 설정은 9가지의 색, 자유롭게 고를 수 있는 1가지, 총 10개로 선택할 수 있도록했습니다.
- hook 파일을 분리하여 선택된 색을 콘솔에 나타나도록 해두었습니다.
- 빨간 원은 리스트 색상으로 props 값으로 `red`를 넘겨줬습니다.
- 카테고리 색 선택(설정)의 색은 `index.css`에 정의해두었고 선택하면 `console.log`에 나타나도록 해두었습니다.
- ex) close #11

design: 카테고리 원형 색상 퍼블리싱

---

src/components/common/TimeInput/TimeInput.stories.tsx
src/components/common/TimeInput/TimeInput.style.ts
src/components/common/TimeInput/TimeInput.tsx

투두, 일정 작성 시 사용되는 시간 입력 컴포넌트입니다 !
```typescript
interface TimeInputProps {
defaultStartTime?: string; // default 시작시간
defaultEndTime?: string; // default 종료시간
withEndTime?: boolean; // 종료시간 옵션 (true: 사용, false: 사용하지 않음)
onChange: (startTime: string, endTime?: string) => void; // 시간 바뀔때마다 호출해서 바뀐 시간 전달
}
``` 
`defaultStartTime?: string;`
09:00으로 기본 설정 해두었는데 수정하실 수 있습니다
</br>
`defaultEndTime?: string;`
10:00으로 기본 설정 해두었고 이것도 수정 가능합니다
</br>
`withEndTime?: boolean;`
일정에서만 종료시간이 필요하기 때문에 옵션으로 넣어뒀습니다
</br>
`onChange: (startTime: string, endTime?: string) => void;`
페이지에서 시간 변경될때마다 전달받는 함수 작성해주시면 됩니다
</br>
시간 선택 부분은 라이브러리를 못찾아서 기본 디자인입니다
라이브러리 괜찮은거 있으면 추천 부탁드려요.. !
시간이 string으로 되어있어서 백엔드로 보낼 때는 time으로 변환하는 함수 만들어서 사용하셔야됩니다 !
- ex) close #22

feat: 시간입력 컴포넌트 구현 및 스토리북 추가

---

src/components/common/ProfileImg/ProfileImg.stories.tsx
src/components/common/ProfileImg/ProfileImg.style.ts
src/components/common/ProfileImg/ProfileImg.tsx

```typescript
interface ProfileImgProps {
size: "large" | "medium" | "small"; // 이미지 크기별 옵션 (필수 입력)
src: string; // 프로필 이미지 소스 (필수 입력)
alt?: string;
}
``` 
large 120*120
medium 30 * 30
small 20 * 20
이미지 사용할때 컴포넌트 이용해서 사이즈 간단하게 설정하시면 됩니다 !
- ex) close #37

feat:프로필 이미지 컴포넌트 구현 및 스토리북 추가

---

src/components/common/ListBar/ListBar.stories.tsx
src/components/common/ListBar/ListBar.style.tsx
src/components/common/ListBar/ListBar.tsx
src/components/common/ScheduleList/ScheduleItem.stories.tsx
src/components/common/ScheduleList/ScheduleItem.style.tsx
src/components/common/ScheduleList/ScheduleItem.tsx
src/components/common/TextDate/TextDate.stories.tsx
src/components/common/TextDate/TextDate.style.tsx
src/components/common/TextDate/TextDate.tsx
src/components/common/TodoList/TodoItem.stories.tsx
src/components/common/TodoList/TodoItem.style.tsx
src/components/common/TodoList/TodoItem.tsx
src/hooks/useCircleInput.ts
src/hooks/useTodoItem.ts

- 투두와 일정을 컴포넌트를 분리해서 제작했습니다.
- 투두 컴포넌트는 개인과 그룹을 하나로 관리하고 있습니다.
- 투두를 완료하고 체크를 누르면 취소선이 나타나게 했습니다.
-  close #27

design: 투두/일정 리스트에 들어가는 내용 퍼블리싱

---

src/components/common/DateInput/DateInput.style.ts
src/components/common/DateInput/DateInput.tsx
src/components/common/SelectList/Category/CategorySelect.style.ts
src/components/common/SelectList/Category/CategorySelect.tsx
src/components/common/SelectList/Group/GroupSelect.style.ts
src/components/common/SelectList/Group/GroupSelect.tsx
src/components/common/TextInput/TextInput.stories.tsx
src/components/common/TextInput/TextInput.style.ts
src/components/common/TextInput/TextInput.tsx
src/components/common/TimeInput/TimeInput.stories.tsx
src/components/common/TimeInput/TimeInput.style.ts
src/components/common/TimeInput/TimeInput.tsx
src/types/input.types.ts
src/types/select.types.ts

`input.types.ts` - TextInput, TimeInput, DateInput 컴포넌트 인터페이스
`select.types.ts` - GroupSelect, CategorySelect 컴포넌트 인터페이스
아래 코드처럼 입력해서 사용하시면 됩니다 
name, type, value, onChange 만 필수 입력
나머지는 옵션으로 추가했습니다
```typescript
const [textInputValue, setTextInputValue] = useState("");
const handleInputChange = (value: string) => {
setTextInputValue(value);
};
``` 
```html
<TextInput
name="input"
type="text"
label="내용"  
placeholder="내용을 입력하세요" 
required={true}  
maxLength={20} 
minLength={2} 
value={textInputValue}  
onChange={handleInputChange}   
/>
``` 
추가적으로 css는 입력 border-bottom 부분 primary 컬러로 수정했습니다
- ex) close #47

refactor: 인터페이스 분리 및 코드 수정

---

src/components/layout/Header/Header.style.ts
src/components/layout/Header/Header.tsx
src/components/layout/RootLayout/RootLayout.tsx

메인페이지, 그룹페이지, 챗봇페이지, 마이페이지 에서는 로고를 보여주고
나머지 페이지에서는 뒤로가기 버튼을 보여줍니다
루트레이아웃에 헤더를 추가해서 모든 페이지에서 확인 가능합니다 !
- ex) close #53

feat: header 구현 및 루트레이아웃 수정

---

src/components/common/Button/Button.tsx
src/components/common/TextInput/TextInput.tsx
src/components/layout/Header/Header.tsx
src/components/layout/NavBar/NavBar.tsx
src/hooks/useSignupForm.ts
src/pages/signup/SignupPage.style.tsx
src/pages/signup/SignupPage.tsx

- 비빌번호와 비밀번호 확인이 일치하지 않으면 일단 `alert("비밀번호가 일치하지 않습니다.");` 처리 해두었습니다.
- `Header.tsx` 헤더를 뒤로가기가 아닌 로고가 나타나도록 했습니다. (알람은 없어져야할 것 같습니다.)
- `NavBar.tsx` 회원가입 페이지에선 네브바가 필요 없으므로 `Header.tsx`를 참고하여 비슷하게 처리했습니다.
- `Button.tsx`에 **type** props를 추가하여 클릭시 onSubmit 이벤트를 넣을 수 있도록 했습니다.
- `TextInput`에서 부모의 `<>~</>` 빈태그를 `<div>~</div>` 으로 수정했습니다. label과 input의 간격이 줄어들었습니다.

design: 회원가입 페이지 퍼블리싱

---

src/components/feature/CategoryList/CategoryList.style.ts
src/components/feature/CategoryList/CategoryList.tsx
src/pages/categories/CategoriesPage.style.ts
src/pages/categories/CategoriesPage.tsx

수정 선택 시에 해당 카테고리의 수정페이지로 이동
삭제를 선택하면 삭제 확인 모달창을 보여줌
하단 내비게이션 바의 z인덱스를 수정해야함
- ex) close #55

feat: 카테고리 생성 페이지 개발

---

src/components/layout/Header/Header.tsx
src/components/layout/NavBar/NavBar.tsx
src/hooks/useLoginForm.ts
src/pages/login/LoginPage.style.ts
src/pages/login/LoginPage.tsx

- 로그인 페이지 퍼블리싱 진행했습니다.
- 값 입력 후 버튼 클릭 시 콘솔에 출력되도록 해두었습니다.
-  close #68

design: 로그인 페이지 퍼블리싱

---

src/components/common/ScheduleList/ScheduleItem.style.tsx
src/components/common/ScheduleList/ScheduleItem.tsx
src/components/common/TodoList/TodoItem.style.tsx
src/components/common/TodoList/TodoItem.tsx
src/components/feature/CategoryList/CategoryList.tsx
src/components/feature/EditDeleteIcon/EditDelete.style.ts
src/components/feature/EditDeleteIcon/EditDeleteIcon.tsx
src/components/feature/MainCategoryButton/MainCategoryButton.style.ts
src/components/feature/MainCategoryButton/MainCategoryButton.tsx
src/components/feature/PlusButton/PlusButton.style.ts
src/components/feature/PlusButton/PlusButton.tsx
src/utils/format.ts

수정 페이지 개발 부분에 맞춰서 나중에 수정필요
현재는 수정페이지로 이동만 가능 
삭제도 현재 ui 상으로만 삭제된 것. 나중에 삭제 구현 필요
카테고리 설정 페이지로 이동은 구현
카테고리 필터링 버튼은 미구현 
각 투두, 일정 생성 페이지로 이동하게 구현
api 에서 받는 데이터 형식에 맞춰서 수정
2024-12-26 => 12월 26일
18:00:00 => 18시 00분
- ex) close #83

feat: 일정, 투두 컴포넌트 기능 구현

---

src/components/feature/CategoryList/CategoryList.style.ts
src/components/feature/CatergoryForm/CategoryForm.style.ts
src/components/feature/MainList/MainList.style.ts
src/components/feature/MainList/MainList.tsx
src/pages/categories/CategoriesPage.style.ts
src/pages/main/MainPage.tsx
src/utils/sortedSchedule.ts
src/utils/sortedTodo.ts

sortedSchedule, sortedTodo 파일에 리스트 정렬부분을 따로 정리했습니다 
투두리스트, 일정리스트가 다 포함된 리스트 컴포넌트 구현했습니다 
현재는 선택 날짜를 임시로 설정해서 선택된 날짜로 데이터들을 필터링 되게 만들었습니다
이부분은 추후에 날짜를 기준으로 일별 데이터를 불러올 수 있는 api 연결해서 사용하면 될 것 같습니다 
카테고리는 임시 데이터로 넣어둬서 사용했습니다 
마찬가지로 삭제도 ui 상으로만 삭제되어 보이고 삭제부분은 나중에 구현 필요합니다 
그리고 달력부분은 주석처리 해두어서 주석 풀어서 사용하시면 됩니다 

feat: mainpage 구현

---

src/pages/group/edit/GroupEditPage.tsx

`routes.tsx` 파일에 `GroupEditPage`에 props 오류가 떠서 안 뜨도록 해결했습니다.
추후 개발에 맞춰 `useParams` 또는 `useLocation` 을 사용해서 데이터를 전달받을 것 같고, 그에 맞춰 수정도 필요합니다.
-  close #95

fix: routes파일 groupEdit  오류 수정

---

src/components/common/Calendar/Calendar.tsx
src/hooks/useCalendar.ts
src/pages/signup/SignupPage.tsx

- svg import 시 대소문자 오류 수정 (yarn build시 svg 대소문자는 에러 메세지로 나타나지 않아서 추가로 알려주시면 수정하겠습니다.)
- `common/Calendar/Calendar.tsx` 에서 {error} -> {error.message} 로 수정
- 임시로 만들어둔 `usePersonalTodos.ts`에서 매개변수 값이 `src/hooks/useCalendar.ts`에서 필요하다고 나타나서 임시 값을 아래와 같이 넣어두었습니다.
```tsx
const {
data: personalTodos = [],
isLoading: isPersonalTodosLoading,
error: personalTodosError,
// 아래의 usePersonalTodos 매개변수 dateParams가 비어있으면 오류가 떠서 임시로 값을 넣었습니다. 수정필요!
} = usePersonalTodos({ year: 2024, month: 12 });
```
- close #105

hotfix: yarn build 오류 수정

---

src/pages/group/noData/GroupNoData.style.ts
src/pages/group/noData/GroupNoData.tsx
src/routes.tsx

- 그룹이 경을 경우 보여줄 페이지
하단 nav 바에서 그룹을 누르게 되면 `/group`으로 이동하게 됩니다.
(적용 X) 이때 그룹 조회 api를 사용하고 그룹이 있다면 `navigate('/group/1')`으로 이동하도록 해두었습니다. 
이는 `useEffect`로 우선 작성 해두었고, 주석처리 해두었습니다.
- close #104

design: 그룹이 없을 경우 페이지 퍼블리싱

---

src/apis/personalSchdule.ts
src/components/common/TextInput/TextInput.tsx
src/hooks/queries/index.ts
src/hooks/queries/usePersonalSchedules.ts
src/hooks/queries/usePersonalTodos.ts
src/hooks/useTodoScheduleForm.ts
src/pages/main/schedule/edit/MainScheduleEditPage.tsx
src/pages/main/schedule/new/MainScheduleNewPage.tsx
src/pages/main/todo/edit/MainTodoEditPage.tsx
src/pages/signup/SignupPage.tsx
src/types/apiRequest.type.ts
src/utils/date.ts

- 개인 일정 생성/수정 API 연결
- 개인 일정 생성/수정 관련 훅 제작
- 개인 일정 생성/수정 관련 타입 정의
- 시간유무, 알림유무 토글 함수 에러 수정
- 로그인, 회원가입 input의 maxLength 변경
- close #126

feat: 개인 일정 생성/수정 API 연결

---

src/apis/apiService.ts
src/apis/group/deleteMember.ts
src/apis/group/getGroup.ts
src/apis/group/getMember.ts
src/apis/group/postGroup.ts
src/apis/group/postInvitation.ts
src/apis/group/putGroup.ts
src/components/feature/GroupNewPage/MemberList.tsx
src/hooks/useGroupEditForm.ts
src/hooks/useGroupNewForm.ts
src/hooks/useInviteMember.ts
src/hooks/useMemberList.ts
src/pages/group/edit/GroupEditPage.tsx
src/pages/group/new/GroupNewPage.tsx
src/pages/group/noData/GroupNoData.tsx
src/store/useAuthStore.ts

groupId와 수정시 필요한 기본 값들은 정적으로 작성해두고 api 연동했습니다.
- 그룹 생성 페이지
- 그룹 생성 
- 그룹 수정 페이지
- 그룹 수정
- 그룹원 조회
- 그룹원 삭제(그룹장)
- 그룹원 초대
- 그룹이 없을 때 렌더링 되는 페이지
- 그룹 조회 (그룹이 있으면 그룹 캘린더로 이동 시켰습니다.)
- close #128

feat: 그룹 페이지 api 연동

---

src/components/feature/main/TodoItem/TodoItem.tsx
src/components/form/TodoScheduleForm/utils.ts
src/hooks/useTodoScheduleForm.ts
src/pages/main/schedule/edit/MainScheduleEditPage.tsx
src/pages/main/schedule/new/MainScheduleNewPage.tsx
src/pages/main/todo/edit/MainTodoEditPage.tsx
src/pages/main/todo/new/MainTodoNewPage.tsx

- 개인 투두 생성 페이지 다른 페이지와 연결
- 개인 투두 수정 페이지 다른 페이지와 연결
- 개인 일정 생성 페이지 다른 페이지와 연결
- 개인 일정 수정 페이지 다른 페이지와 연결
- close #143

feat: 개인 투두&일정의 생성&수정 페이지 다른 페이지와 연결

---

src/apis/categories.ts
src/components/common/SelectList/Category/CategorySelect.tsx
src/components/feature/CategoryList/CategoryList.tsx
src/components/feature/CatergoryForm/CategoryForm.style.ts
src/components/feature/CatergoryForm/CategoryForm.tsx
src/hooks/queries/index.ts
src/hooks/queries/useCategories.ts
src/hooks/useCategoryForm.ts
src/pages/categories/CategoriesPage.style.ts
src/pages/categories/CategoriesPage.tsx
src/pages/categories/edit/CategoriesEditPage.tsx
src/pages/categories/new/CategoriesNewPage.tsx

```typescript
// 개인 카테고리만 조회
export const useGetPersonalCategories = () => {
return useQuery({
queryKey: ["categories"],
queryFn: () => getCategories(),
select: (response) => ({
...response,
data: response.data.filter((category: Category) => !category.groupId),
}),
});
};
``` 
- ex) close #135

feat: 카테고리 api 연결 및 수정

---

src/components/feature/group/MainList/GroupList.tsx
src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
src/pages/group/schedule/new/GroupScheduleNewPage.tsx
src/pages/group/todo/edit/GroupTodoEditPage.tsx
src/pages/group/todo/new/GroupTodoNewPage.tsx

- 이전 페이지에서 넘겨주는 props값 변경
- 그룹 투두 생성 페이지 다른 페이지와 연결
- 그룹 투두 수정 페이지 다른 페이지와 연결
- 그룹 투두 생성 페이지 다른 페이지와 연결
- 그룹 일정 수정 페이지 다른 페이지와 연결
- close #149

feat: 그룹 투두/일정 생성/수정 페이지 다른 페이지와 연결

---

src/components/feature/GroupNewPage/MemberList.tsx
src/hooks/useGroupEditForm.ts
src/pages/group/edit/GroupEditPage.tsx
src/pages/group/noData/GroupNoData.tsx

- 그룹 여부에 따라 페이지 이동이 적용되지 않았던 부분을 수정 했습니다.
- 그룹 수정페이지에 데이터들을 `location state`로 연결했습니다.
- 수정 api가 동작하는 것을 확인 했습니다.
- 그룹원 삭제 api는 그룹원이어서 확인을 못했지만 에러 메시지(접근 권한이 없습니다)를 toast 메세지로 띄웠습니다.
- close #151

feat: 그룹 데이터 없을 경우 및 수정 페이지 로직 수정
